metadata {
    summary: "The Mikmod audio module developer library (common)";
    description: @"Mikmod is a module player and library supporting many formats, including mod, s3m, it, and xm.";
    
    author-version : "${author-version}";
    bug-tracker: "https://github.com/coapp-packages/libmikmod/issues";
    stability : "0";
    licenses : {
        "lgpl2+"
    };
}

license[lgpl2+] {
    license-url: "http://www.gnu.org/licenses/lgpl-2.1.html";
    license-type: "lgpl";
}
